import type { PricePackages } from "@/app/_types";

export const packagesData: PricePackages[] = [
  {
    id: 1,
    variant: "default",
    title: "Start Up",
    description: "For first-time authors stepping into print.",
    newPrice: 299,
    oldPrice: 500,
    period: "One-Time",
    badge: null,
    features: [
      { label: "Manuscript Prep", included: true },
      { label: "Editorial Support", included: true },
      { label: "Proofreading", included: true },
      { label: "Typesetting", included: true },
      { label: "2 Revisions", included: true },
      { label: "Cover Prep", included: true },
    ],
  },
  {
    id: 2,
    variant: "primary",
    title: "Standard",
    description: "Our most popular launch package.",
    newPrice: 1050,
    oldPrice: 1500,
    period: "One-Time",
    badge: null,
    features: [
      { label: "Everything in Start Up", included: true },
      { label: "Pro Formatting", included: true },
      { label: "3 Revisions", included: true },
      { label: "Custom Cover", included: true },
      { label: "ISBN Assignment", included: true },
      { label: "Distribution Setup", included: true },
    ],
  },
  {
    id: 3,
    variant: "secondary",
    title: "Authors Elite",
    description: "End-to-end concierge publishing.",
    newPrice: 1749,
    oldPrice: 3500,
    period: "One-Time",
    badge: "Most Sold",
    features: [
      { label: "Everything in Standard", included: true },
      { label: "5 Revisions", included: true },
      { label: "Premium Cover Design", included: true },
      { label: "Marketing Strategy", included: true },
      { label: "Amazon Optimization", included: true },
      { label: "Author Coaching", included: true },
    ],
  },
];
